apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-container
  template:
    metadata:
      labels:
        app: my-container
    spec:
      containers:
      - name: my-app-container
        image: zeynep02/my-app-v7:latest
        ports:
        - containerPort: 5000
