apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app 
  replicas: 2 # Specify the number of pods to run
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app:latest # Specify the image to usemy 
        ports:
        - containerPort: 5000 # Specify the port to expose
        volumeMounts:
        - name: my-app-valume
          mountPath: /app
         # /var/lib/docker/volumes/minikube/_data #Specify the mounth path in the container     

      volumes:
      - name: my-app-valume
        hostPath:
          path: home/ozelz/npc1/data
          type: Directory
       # persistentVolumeClaim:
         # claimName: my-data-pvc   # Name of the PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
