apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app 
  replicas: 5 # Specify the number of pods to run
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: zeynep02/my-app-v3 # Specify the image to usemy 
        ports:
        - containerPort: 5000 # Specify the port to expose
        resources:
        volumeMounts:
        - name: my-app-valume
          mountPath: /app #Specify the mounth path in the container  
      volumes:
      - name: my-app-valume
      persistentVolumeClaim:
         claimName: my-data-pvc   # Name of the PersistentVolumeClaim
        '''hostPath:
          path: home/ozelz/npc1/data
          type: Directory'''
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: Simulation_MLOPS_Equasim
spec:
  desc: Allow access to Kubeflow Pipelines
  selector:
    matchLabels:
      access-ml-pipeline: "true"

'''apiVersion: v1
kind: StorageClass
metadata:
  name: my-data-storage
provisioner: ''' 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-data-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/ozelz/npc1/data
