apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: kubeflow-user-example-com
type: Opaque
data:
  accesskey: loICkyAu0tFpBdFc9Oio
  secretkey: OnZeoKkKDJB9mhpVVDqWMUIUM1psTTfSexncvD7G

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-kserve
  namespace: kubeflow-user-example-com
secrets:
- name: minio-credentials