apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: kubeflow-user-example-com
spec:
  selector:
    matchLabels:
      app: my-app 
  replicas: 4 # Specify the number of pods to run
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
        - name: my-app-volume
          persistentVolumeClaim:
            claimName: my-data-pv   # Name of the PersistentVolumeClaim
      containers:
        - name: my-app-container
          image: zeynep02/my-app-v4:latest # Specify the image to usemy 
          ports:
          - containerPort: 5000 # Specify the port to expose
          resources:
          volumeMounts:
            - name: my-app-volume
              mountPath: /app #Specify the mounth path in the container  
      
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
