apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-app-determine-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
