apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-deployment
  namespace: kubeflow-user-example-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-container
  template:
    metadata:
      labels:
        app: my-container
    spec:
      containers:
      - name: my-test-container
        image: zeynep02/pipeline-v0.0.4:latest
        ports:
        - containerPort: 5000
        resources:                  # Corrected field name
        volumeMounts:
        - mountPath: /app
          name: my-storage
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: my-pvc-mnt
